### ISSUE TITLE
Hide Trajectory loader when swirching to different run

### ISSUE THREAD

**Issue by amjha** [corning-incorporated/citam#290]
**Describe the bug**
Behavior of Trajectory Loader component should be aligned with RUN option changes.
Show this component when switching to a different RUN and hide it when loading is completed.

**To Reproduce**
1. Open a RUN
2. Trajectory loader starts and keeps spinning
3. Switch to another RUN
4. Trajectory loader keeps spinning 

**Expected behavior**
Loader starts/stops with RUN data

**Comment by mreveil** [comment]
Resolved as part of release/0.15.
